### PR TITLE
update virtualbox ext to 4.3.26

### PR DESCRIPTION
**Pull request by cfoellmann**

### CODE REVIEW

**Comment by ferventcoder** [comment]
@cfoellmann I take it this never made it in?

**Comment by ferventcoder** [comment]
Although it appears that there have been updates since.

**Comment by cfoellmann** [comment]
I didn't follow up since updating virtual box through Choco did give me too much trouble.
Should be an automatic package anyway

**Comment by ferventcoder** [comment]
This was a pull request - it was closed. I was simply stating that the PR was not accepted but it appears that the package itself has moved forward since then.

**Pull request closed without merging**
