### PR TITLE
Bump Leiningen to 2.6.1

### PR DESCRIPTION
**Pull request by winks**
Update version and remove obsolete hard curl dependency

### CODE REVIEW

**Comment by winks** [comment]
If you are not interested in being the maintainer of https://chocolatey.org/packages/Lein - I think I can take over. Would be cool if I was allowed to reuse your current code though :)

**Comment by tutysara** [comment]
oops, did a pull request and found there is a request already ;). Why was this still not merged?

**Comment by ForNeVeR** [comment]
@winks there's a [Package Triage Process](https://chocolatey.org/docs/package-triage-process#package-is-outdated). Have you tried to follow it?

We really need some active maintainers for lein package, because it creates problems for everybody: https://github.com/technomancy/leiningen/issues/2139

**Comment by winks** [comment]
@ForNeVeR nope, I kinda forgot about this.

Gonna prepare a patch for current 2.7.1 and try to get this sorted.

**Pull request closed without merging**
